from abc import ABC, abstractmethod
from datetime import datetime, timedelta
from functools import cached_property
from pathlib import Path

import numpy as np
import pytest
import xarray as xr
from pydantic import BaseModel

from regrid_wrapper.app.chem_regrid.context import ChemRegridContext, DatasetName
from regrid_wrapper.context.comm import COMM
from test.conftest import create_analytic_data_array, create_rrfs_grid_file


class SpatialSpec(BaseModel):
    """
    Defines the spatial domain for generating synthetic test data.
    """

    min_lon: float
    max_lon: float
    min_lat: float
    max_lat: float
    nlon: int = 71
    nlat: int = 26


class FieldMeta(BaseModel):
    """
    Metadata for a field used to verify correctness of regridding operations.
    """

    shape: tuple[int, ...]
    sum: float


class DatasetTestContext(ABC, BaseModel):
    """
    Abstract base class for dataset-specific test contexts.

    This class provides a framework for creating input data files, defining
    expected results, and verifying output data for integration tests.
    """

    # Directory where input data files are created.
    input_dir: Path
    # Directory where regridded output files are saved.
    output_dir: Path
    # Directory where ESMF weight files are stored.
    weight_dir: Path
    # Path to the UGRID file used for regridding.
    ugrid_path: Path
    # Directory containing task-local (i.e., temporary work) data
    work_dir: Path

    # Required overrides in subclasses =====

    # Name of the dataset being tested.
    key: DatasetName
    # Dictionary mapping field names to their expected sums in the output.
    expected_sums: dict[str, float]
    # The expected shape of fields in the output files.
    expected_field_shape: tuple[int, ...]
    # Expected sum of the "S" variable in the weight file.
    expected_weight_sum: float
    # Expected value of the "n_s" dimension in the weight file.
    expected_weight_ns: int

    # Optional overrides in subclasses =====

    # Expected dimension names
    expected_dim_names: tuple[str, ...] = ("nCells",)
    # Number of decimal places to use for sum verification.
    expected_sum_decimal: int = 7
    # Dictionary mapping field names to their expected shapes for fields that deviate from the default.
    expected_field_shape_exceptions: dict[str, tuple[int, ...]] = {}

    @abstractmethod
    def create_input_data_files(self) -> None:
        """
        Creates the input data files required for the test.
        Must be implemented by subclasses.
        """
        ...

    @property
    def field_names(self) -> list[str]:
        """
        Returns a list of field names to be processed.
        """
        return list(self.expected_sums.keys())

    @cached_property
    def spatial_spec(self) -> SpatialSpec:
        """
        Derives the spatial specification from the target UGRID file.
        """
        with xr.open_dataset(self.ugrid_path) as ds:
            buffer = 10
            return SpatialSpec(
                min_lon=float(ds.node_lon.min()) - buffer,
                max_lon=float(ds.node_lon.max()) + buffer,
                min_lat=float(ds.node_lat.min()) - buffer,
                max_lat=float(ds.node_lat.max()) + buffer,
            )

    @cached_property
    def actual_field_meta(self) -> dict[str, dict[str, FieldMeta]]:
        """
        Calculates actual metadata (shape and sum) for fields in the output files.
        """
        ret = {}
        for output_file in self.output_files:
            with xr.open_dataset(output_file) as ds:
                ret[output_file.name] = {
                    field: FieldMeta(shape=ds[field].shape, sum=float(ds[field].sum())) for field in self.field_names
                }
        return ret

    @property
    def output_files(self) -> list[Path]:
        """
        Returns a sorted list of output files generated by the regridding application.
        """
        return sorted(list(self.output_dir.glob("*")))

    def verify_output_data_files(self) -> None:
        """
        Verifies that the output data files contain the expected fields with correct shapes and sums.
        """
        for output_file in self.output_files:
            with xr.open_dataset(output_file) as ds:
                for field_name in self.field_names:
                    target = ds[field_name]
                    expected_shape = self.expected_field_shape_exceptions.get(field_name, self.expected_field_shape)
                    assert target.shape == expected_shape
                    assert target.dims == self.expected_dim_names
                    np.testing.assert_almost_equal(
                        self.actual_field_meta[output_file.name][field_name].sum,
                        self.expected_sums[field_name],
                        decimal=self.expected_sum_decimal,
                    )

    def verify_weight_files(self) -> None:
        """
        Verifies that the weight files contain the expected n_s dimension and S variable sum.
        """
        weight_files = list(self.weight_dir.glob("*.nc"))
        assert len(weight_files) == 1
        with xr.open_dataset(weight_files[0]) as ds:
            assert ds.sizes["n_s"] == self.expected_weight_ns
            np.testing.assert_almost_equal(float(ds["S"].sum()), self.expected_weight_sum, decimal=self.expected_sum_decimal)


class RAVE_DatasetTestContext(DatasetTestContext):
    key: DatasetName = DatasetName.RAVE
    expected_field_shape: tuple[int, ...] = (1, 162, 1)
    expected_dim_names: tuple[str, ...] = ("Time", "nCells", "nkwildfire")
    expected_weight_ns: int = 6109
    expected_weight_sum: float = 168.59977032981334
    expected_sums: dict[str, float] = {
        "TPM": 85.65801452561297,
        "FRE": 308.36885229220667,
        "FRP_MEAN": 308.36885229220667,
        "PM25": 85.65801452561297,
        "NH3": 5.038706736800762,
        "SO2": 0.08565801452561297,
        "CH4": 5.353625907850811,
        "CO": 3.059214804486177,
        "NOx": 2.3586989507052842,
    }

    def create_input_data_files(self) -> None:
        # Create RAVE input files for the 25 iterations of the dates_needed loop
        for i in range(25):
            date_dt = datetime(2026, 4, 8, 9) + timedelta(hours=i)
            date_str = date_dt.strftime("%Y%m%d%H")
            # find_latest_rave_file looks for "RAVE-HrlyEmiss-3km_v2r0_blend_s" + date_to_process
            rave_filename = f"RAVE-HrlyEmiss-3km_v2r0_blend_s{date_str}_e{date_str}_v2.nc"
            rave_path = self.input_dir / rave_filename
            self._create_rave_file_from_ugrid_(rave_path)

    def _create_rave_file_from_ugrid_(self, output_path: Path) -> None:
        if COMM.rank == 0:
            create_rrfs_grid_file(
                output_path,
                fields=self.field_names,
                min_lon=self.spatial_spec.min_lon,
                max_lon=self.spatial_spec.max_lon,
                min_lat=self.spatial_spec.min_lat,
                max_lat=self.spatial_spec.max_lat,
                ntime=1,
                nlon=self.spatial_spec.nlon,
                nlat=self.spatial_spec.nlat,
            )
        COMM.barrier()


class GRA2PES_DatasetTestContext(DatasetTestContext):
    key: DatasetName = DatasetName.GRA2PES
    expected_field_shape: tuple[int, ...] = (12, 162, 20)
    expected_dim_names: tuple[str, ...] = ("Time", "nCells", "nkanthro")
    expected_sum_decimal: int = 6
    expected_weight_ns: int = 6109
    expected_weight_sum: float = 168.59977032981334
    expected_sums: dict[str, float] = {
        "PM25-PRI": 1403078277.9295404,
        "PM10-PRI": 1403078277.9295404,
        "SO2": 0.0014030782779295404,
        "CO": 0.0014030782779295404,
        "NOX": 0.0014030782779295404,
        "NH3": 0.0014030782779295404,
        "h_agl": 5051081.800546346,
    }

    def create_input_data_files(self) -> None:
        fns = ("GRA2PESv1.0_total_202104_weekdy_00to11Z.nc", "GRA2PESv1.0_total_202104_weekdy_12to23Z.nc")
        for fn in fns:
            outpath = self.input_dir / fn
            self._create_gra2pes_grid_file_(outpath)

    def _create_gra2pes_grid_file_(self, path: Path) -> None:
        if path.exists():
            raise ValueError(f"path exists: {path}")
        if COMM.rank == 0:
            lon = np.linspace(self.spatial_spec.min_lon, self.spatial_spec.max_lon, self.spatial_spec.nlon)
            lat = np.linspace(self.spatial_spec.min_lat, self.spatial_spec.max_lat, self.spatial_spec.nlat)
            lon_mesh, lat_mesh = np.meshgrid(lon, lat)
            ds = xr.Dataset()
            spatial_dims = ["south_north", "west_east"]
            ds["XLONG"] = xr.DataArray(lon_mesh, dims=spatial_dims)
            ds["XLAT"] = xr.DataArray(lat_mesh, dims=spatial_dims)

            lonc = np.hstack((lon - 0.5, [lon[-1] + 0.5]))
            latc = np.hstack((lat - 0.5, [lat[-1] + 0.5]))
            lonc_mesh, latc_mesh = np.meshgrid(lonc, latc)
            ds["XLONG_C"] = xr.DataArray(lonc_mesh, dims=["south_north_stag", "west_east_stag"])
            ds["XLAT_C"] = xr.DataArray(latc_mesh, dims=["south_north_stag", "west_east_stag"])

            for field_name in self.field_names:
                if field_name == "h_agl":
                    level_dimname = "bottom_top_stag"
                else:
                    level_dimname = "bottom_top"
                data_dims = ["Time", level_dimname] + spatial_dims
                ds[field_name] = create_analytic_data_array(data_dims, lon_mesh, lat_mesh, ntime=12, nlevel=20)
            ds.to_netcdf(path)
        COMM.barrier()


class FMC_DatasetTestContext(DatasetTestContext):
    key: DatasetName = DatasetName.FMC
    expected_field_shape: tuple[int, ...] = (1, 162, 1)
    expected_dim_names: tuple[str, ...] = ("Time", "nCells", "nkwildfire")
    expected_sum_decimal: int = 6
    expected_weight_ns: int = 648
    expected_weight_sum: float = 162.0
    expected_sums: dict[str, float] = {
        "10h_dead_fuel_moisture_content": 298.16085159384863,
    }

    def create_input_data_files(self) -> None:
        # Create FMC input files for the 25 iterations
        # FMC implementation uses: datetime(int(YYYY), int(MM), int(DD), int(HH), 0, 0) - timedelta(hours=i)
        # where YYYYMMDDHH is from cycle. cycle is 2026040809
        for i in range(25):
            date_dt = datetime(2026, 4, 8, 9) - timedelta(hours=i)
            date_str = date_dt.strftime("%Y%m%d%H")
            filename = f"fmc_{date_str}.nc"
            path = self.input_dir / filename
            self._create_fmc_file_(path)

    def _create_fmc_file_(self, path: Path) -> None:
        if COMM.rank == 0:
            lon = np.linspace(self.spatial_spec.min_lon, self.spatial_spec.max_lon, self.spatial_spec.nlon)
            lat = np.linspace(self.spatial_spec.min_lat, self.spatial_spec.max_lat, self.spatial_spec.nlat)
            lon_mesh, lat_mesh = np.meshgrid(lon, lat)
            ds = xr.Dataset()
            spatial_dims = ["ny", "nx"]
            ds["longitude"] = xr.DataArray(lon_mesh, dims=spatial_dims)
            ds["latitude"] = xr.DataArray(lat_mesh, dims=spatial_dims)

            for field_name in self.field_names:
                data_dims = ["time"] + spatial_dims
                ds[field_name] = create_analytic_data_array(data_dims, lon_mesh, lat_mesh, ntime=1)
            ds.to_netcdf(path)
        COMM.barrier()


class NEMO_RWC_DatasetTestContext(DatasetTestContext):
    key: DatasetName = DatasetName.NEMO_RWC
    expected_field_shape: tuple[int, ...] = (1, 162)
    expected_sum_decimal: int = 6
    expected_dim_names: tuple[str, ...] = ("Time", "nCells")
    expected_weight_ns: int = 6109
    expected_weight_sum: float = 168.59977032981334
    expected_sums: dict[str, float] = {
        "POC": 308.36885229220667,
        "PEC": 308.36885229220667,
        "PMOTHR": 308.36885229220667,
        "PMC": 308.36885229220667,
    }

    def create_input_data_files(self) -> None:
        filename = "NEMO_RWC_POC_PEC_PMOTHR.annual.2017.nc"
        path = self.input_dir / filename
        self._create_nemo_file_(path, time_name="Time")

    def _create_nemo_file_(self, path: Path, time_name: str, has_lay: bool = False) -> None:
        if COMM.rank == 0:
            lon = np.linspace(self.spatial_spec.min_lon, self.spatial_spec.max_lon, self.spatial_spec.nlon)
            lat = np.linspace(self.spatial_spec.min_lat, self.spatial_spec.max_lat, self.spatial_spec.nlat)
            lon_mesh, lat_mesh = np.meshgrid(lon, lat)

            lonc = np.hstack((lon - 0.5, [lon[-1] + 0.5]))
            latc = np.hstack((lat - 0.5, [lat[-1] + 0.5]))
            lonc_mesh, latc_mesh = np.meshgrid(lonc, latc)

            ds = xr.Dataset()
            ds["lon"] = xr.DataArray(lon_mesh, dims=["ROW", "COL"])
            ds["lat"] = xr.DataArray(lat_mesh, dims=["ROW", "COL"])
            ds["lonc"] = xr.DataArray(lonc_mesh, dims=["ROWC", "COLC"])
            ds["latc"] = xr.DataArray(latc_mesh, dims=["ROWC", "COLC"])

            for field_name in self.field_names:
                data_dims = [time_name]
                if has_lay:
                    data_dims.append("LAY")
                data_dims.extend(["ROW", "COL"])
                ds[field_name] = create_analytic_data_array(data_dims, lon_mesh, lat_mesh, ntime=1, nlevel=1 if has_lay else None)
            ds.to_netcdf(path)
        COMM.barrier()


class NEMO_ANTHRO_DatasetTestContext(NEMO_RWC_DatasetTestContext):
    key: DatasetName = DatasetName.NEMO_ANTHRO
    expected_field_shape: tuple[int, ...] = (1, 162, 1)
    expected_dim_names: tuple[str, ...] = ("Time", "nCells", "nkanthro")
    expected_weight_ns: int = 6109
    expected_weight_sum: float = 168.59977032981334

    def create_input_data_files(self) -> None:
        # NEMO_ANTHRO_test_mesh_2026040809_SECTORSUM.nc
        filename = "NEMO_ANTHRO_test_mesh_2026040809_SECTORSUM.nc"
        path = self.input_dir / filename
        self._create_nemo_file_(path, time_name="TSTEP", has_lay=True)


class PECM_DatasetTestContext(NEMO_RWC_DatasetTestContext):
    key: DatasetName = DatasetName.PECM
    expected_field_shape: tuple[int, ...] = (1, 162, 1)
    expected_dim_names: tuple[str, ...] = ("Time", "nCells", "nkbiogenic")
    expected_weight_ns: int = 6109
    expected_weight_sum: float = 168.59977032981334
    expected_sums: dict[str, float] = {
        "DBL_POLL": 308.36885229220667,
        "ENL_POLL": 308.36885229220667,
        "GRA_POLL": 308.36885229220667,
        "RAG_POLL": 308.36885229220667,
        "TREE_POLL": 308.36885229220667 * 2,
    }

    def create_input_data_files(self) -> None:
        # pollen_obs_2026_BELD6_ef_T_098.nc
        filename = "pollen_obs_2026_BELD6_ef_T_098.nc"
        path = self.input_dir / filename
        self._create_nemo_file_(path, time_name="time")


class NARR_DatasetTestContext(DatasetTestContext):
    key: DatasetName = DatasetName.NARR
    expected_field_shape: tuple[int, ...] = (1, 162)
    expected_dim_names: tuple[str, ...] = ("Time", "nCells")
    expected_sum_decimal: int = 6
    expected_weight_ns: int = 648
    expected_weight_sum: float = 162.0
    expected_sums: dict[str, float] = {
        "RWC_denominator": 298.16085159384863,
    }

    def create_input_data_files(self) -> None:
        filename = "rwc_emission_denominator.2017.nc"
        path = self.input_dir / filename
        self._create_narr_file_(path)

    def _create_narr_file_(self, path: Path) -> None:
        if COMM.rank == 0:
            lon = np.linspace(self.spatial_spec.min_lon, self.spatial_spec.max_lon, self.spatial_spec.nlon)
            lat = np.linspace(self.spatial_spec.min_lat, self.spatial_spec.max_lat, self.spatial_spec.nlat)
            lon_mesh, lat_mesh = np.meshgrid(lon, lat)
            ds = xr.Dataset()
            spatial_dims = ["y", "x"]
            ds["lon"] = xr.DataArray(lon_mesh, dims=spatial_dims)
            ds["lat"] = xr.DataArray(lat_mesh, dims=spatial_dims)

            for field_name in self.field_names:
                data_dims = ["Time"] + spatial_dims
                ds[field_name] = create_analytic_data_array(data_dims, lon_mesh, lat_mesh, ntime=1)
            ds.to_netcdf(path)
        COMM.barrier()


class ECOREGION_DatasetTestContext(DatasetTestContext):
    key: DatasetName = DatasetName.ECOREGION
    expected_field_shape: tuple[int, ...] = (1, 162, 1)
    expected_dim_names: tuple[str, ...] = ("Time", "nCells", "nkwildfire")
    expected_sum_decimal: int = 6
    expected_weight_ns: int = 162
    expected_weight_sum: float = 162.0
    expected_sums: dict[str, float] = {
        "ecoregion_ID": 297.64325399359495,
    }

    def create_input_data_files(self) -> None:
        filename = "veg_map.nc"
        path = self.input_dir / filename
        self._create_ecoregion_file_(path)

    def _create_ecoregion_file_(self, path: Path) -> None:
        if COMM.rank == 0:
            lon = np.linspace(self.spatial_spec.min_lon, self.spatial_spec.max_lon, self.spatial_spec.nlon)
            lat = np.linspace(self.spatial_spec.min_lat, self.spatial_spec.max_lat, self.spatial_spec.nlat)
            lon_mesh, lat_mesh = np.meshgrid(lon, lat)
            ds = xr.Dataset()
            spatial_dims = ["lat", "lon"]
            ds["geolon"] = xr.DataArray(lon_mesh, dims=spatial_dims)
            ds["geolat"] = xr.DataArray(lat_mesh, dims=spatial_dims)

            for field_name in self.field_names:
                data_dims = ["time"] + spatial_dims
                ds[field_name] = create_analytic_data_array(data_dims, lon_mesh, lat_mesh, ntime=1)
            ds.to_netcdf(path)
        COMM.barrier()


class FENGSHA_2D_DatasetTestContext(DatasetTestContext):
    key: DatasetName = DatasetName.FENGSHA_2D
    expected_field_shape: tuple[int, ...] = (162,)
    expected_sum_decimal: int = 6
    expected_weight_ns: int = 648
    expected_weight_sum: float = 162.0
    expected_sums: dict[str, float] = {
        "clayfrac": 298.16085159384863,
        "sandfrac": 298.16085159384863,
        "uthres": 298.16085159384863,
        "ssm": 298.16085159384863,
    }

    def create_input_data_files(self) -> None:
        filename = "FENGSHA_RRFS_NA_3km_2026_2D.nc"
        path = self.input_dir / filename
        self._create_fengsha_file_(path, time_size=0)

    def _create_fengsha_file_(self, path: Path, time_size: int) -> None:
        if COMM.rank == 0:
            lon = np.linspace(self.spatial_spec.min_lon, self.spatial_spec.max_lon, self.spatial_spec.nlon)
            lat = np.linspace(self.spatial_spec.min_lat, self.spatial_spec.max_lat, self.spatial_spec.nlat)
            lon_mesh, lat_mesh = np.meshgrid(lon, lat)
            ds = xr.Dataset()
            spatial_dims = ["lat", "lon"]
            ds["longitude"] = xr.DataArray(lon_mesh, dims=spatial_dims)
            ds["latitude"] = xr.DataArray(lat_mesh, dims=spatial_dims)

            for field_name in self.field_names:
                if time_size > 0:
                    data_dims = ["time"] + spatial_dims
                    ds[field_name] = create_analytic_data_array(data_dims, lon_mesh, lat_mesh, ntime=time_size)
                else:
                    data_dims = spatial_dims
                    ds[field_name] = create_analytic_data_array(data_dims, lon_mesh, lat_mesh)
            ds.to_netcdf(path)
        COMM.barrier()


class FENGSHA_2D_Time_DatasetTestContext(FENGSHA_2D_DatasetTestContext):
    key: DatasetName = DatasetName.FENGSHA_2D_Time
    expected_field_shape: tuple[int, ...] = (12, 162)
    expected_dim_names: tuple[str, ...] = ("Time", "nCells")
    expected_weight_ns: int = 648
    expected_weight_sum: float = 162.0
    expected_sums: dict[str, float] = {
        "rdrag": 23256.546424320197,
    }

    def create_input_data_files(self) -> None:
        filename = "FENGSHA_RRFS_NA_3km_2026_2D_Time.nc"
        path = self.input_dir / filename
        self._create_fengsha_file_(path, time_size=12)


class GOES_DatasetTestContext(DatasetTestContext):
    key: DatasetName = DatasetName.GOES
    expected_field_shape: tuple[int, ...] = (162,)
    expected_weight_ns: int = 648
    expected_weight_sum: float = 162.0
    expected_sums: dict[str, float] = {
        "AOD": 298.16082763671875,
    }

    @property
    def output_files(self) -> list[Path]:
        """
        Returns a sorted list of output files generated by the regridding application.
        """
        return sorted(list(self.output_dir.glob("*-GOES-*")))

    def create_input_data_files(self) -> None:
        date_dt = datetime(2026, 4, 8, 9)
        date_str = date_dt.strftime("%Y%j%H")
        # OR_ABI-L2-AODC-M6_G18_s%Y%j%H*
        filename = f"OR_ABI-L2-AODC-M6_G18_s{date_str}12345.nc"
        path = self.input_dir / filename
        self._create_goes_file_(path)

        coord_path = self.work_dir / "goes19_abi_conus_interpolated_lat_lon.nc"
        self._create_goes_file_(coord_path)

    def _create_goes_file_(self, path: Path) -> None:
        if COMM.rank == 0:
            lon = np.linspace(self.spatial_spec.min_lon, self.spatial_spec.max_lon, self.spatial_spec.nlon)
            lat = np.linspace(self.spatial_spec.min_lat, self.spatial_spec.max_lat, self.spatial_spec.nlat)
            lon_mesh, lat_mesh = np.meshgrid(lon, lat)
            ds = xr.Dataset()
            # GOES implementation expects dimensions "x", "y"
            # and coordinates "longitude", "latitude"
            spatial_dims = ["y", "x"]
            ds["longitude"] = xr.DataArray(lon_mesh, dims=spatial_dims)
            ds["latitude"] = xr.DataArray(lat_mesh, dims=spatial_dims)

            for field_name in self.field_names:
                data_dims = spatial_dims
                ds[field_name] = create_analytic_data_array(data_dims, lon_mesh, lat_mesh)
            ds.to_netcdf(path)
        COMM.barrier()


@pytest.fixture(
    params=[
        DatasetName.RAVE,
        DatasetName.GRA2PES,
        DatasetName.FMC,
        DatasetName.NEMO_RWC,
        DatasetName.NEMO_ANTHRO,
        DatasetName.PECM,
        DatasetName.NARR,
        DatasetName.ECOREGION,
        DatasetName.FENGSHA_2D,
        DatasetName.FENGSHA_2D_Time,
        DatasetName.GOES,
    ]
)
def dataset_test_ctx(request: pytest.FixtureRequest, tmp_path_shared: Path, ugrid_path: Path) -> DatasetTestContext:
    input_dir = tmp_path_shared / "input"
    output_dir = tmp_path_shared / "output"
    weight_dir = tmp_path_shared / "weights"
    work_dir = tmp_path_shared / "work"

    dataset_map = {
        DatasetName.RAVE: RAVE_DatasetTestContext,
        DatasetName.GRA2PES: GRA2PES_DatasetTestContext,
        DatasetName.FMC: FMC_DatasetTestContext,
        DatasetName.NEMO_RWC: NEMO_RWC_DatasetTestContext,
        DatasetName.NEMO_ANTHRO: NEMO_ANTHRO_DatasetTestContext,
        DatasetName.PECM: PECM_DatasetTestContext,
        DatasetName.NARR: NARR_DatasetTestContext,
        DatasetName.ECOREGION: ECOREGION_DatasetTestContext,
        DatasetName.FENGSHA_2D: FENGSHA_2D_DatasetTestContext,
        DatasetName.FENGSHA_2D_Time: FENGSHA_2D_Time_DatasetTestContext,
        DatasetName.GOES: GOES_DatasetTestContext,
    }

    klass = dataset_map[request.param]
    return klass.model_validate(
        dict(input_dir=input_dir, ugrid_path=ugrid_path, output_dir=output_dir, weight_dir=weight_dir, work_dir=work_dir)
    )


@pytest.fixture
def chem_regrid_context(tmp_path_shared: Path, dataset_test_ctx: DatasetTestContext) -> ChemRegridContext:
    if COMM.rank == 0:
        dataset_test_ctx.work_dir.mkdir(exist_ok=True)
        dataset_test_ctx.input_dir.mkdir(exist_ok=True)
        dataset_test_ctx.output_dir.mkdir(exist_ok=True)
        dataset_test_ctx.weight_dir.mkdir(exist_ok=True)
    COMM.barrier()

    cycle = "2026040809"
    ebb_dcycle = 1  # same-day

    dataset_test_ctx.create_input_data_files()

    # Create dummy destination file (MPAS grid)
    # The main() reads num_cells from dst_path
    dst_path = dataset_test_ctx.work_dir / "init.nc"
    ds_dst = xr.Dataset()
    num_cells = 162
    ds_dst["latCell"] = xr.DataArray(np.ones(num_cells), dims=["nCells"])
    ds_dst["lonCell"] = xr.DataArray(np.ones(num_cells), dims=["nCells"])
    ds_dst["areaCell"] = xr.DataArray(np.ones(num_cells), dims=["nCells"])
    ds_dst["xtime"] = xr.DataArray(np.ones(num_cells), dims=["nCells"])
    if COMM.rank == 0:
        ds_dst.to_netcdf(dst_path)
    COMM.barrier()

    # Create ChemRegridContext
    ctx = ChemRegridContext(
        dataset_name=dataset_test_ctx.key,
        workdir=dataset_test_ctx.work_dir,
        input_dir=dataset_test_ctx.input_dir,
        output_dir=dataset_test_ctx.output_dir,
        weight_dir=dataset_test_ctx.weight_dir,
        cycle=cycle,
        mesh_name="test_mesh",
        scrip_path=dataset_test_ctx.ugrid_path,
        dst_path=dst_path,
        ebb_dcycle=ebb_dcycle,
        fcst_length=24,
    )
    return ctx
