FROM ubuntu:24.04

RUN apt-get update --yes && apt-get install --yes tmux \
  vim \
  less \
  git \
  build-essential \
  python3 \
  python3-dev \
  gfortran \
  cmake \
  curl \
  ca-certificates \
#  libopenmpi-dev \
  libcurl4-openssl-dev \
#  libopenblas-dev \
#  liblapack-dev \
#  libpcre2-dev \
#  libpcre2-16-0 \
#  libpcre2-32-0 \
#  libgsl-dev \
#  m4 \
  tar \
  gettext \
  libgettextpo-dev \
#  ninja-build \
  nco \
#  libaec-dev \
#  libsz2 \
  && apt-get purge -y --auto-remove \
  && rm -rf /var/lib/apt/lists/*

ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --default-toolchain stable

WORKDIR /opt/regrid-wrapper
RUN git clone --depth=1 --recurse-submodules https://github.com/JCSDA/spack-stack
WORKDIR spack-stack
ENV SPACK_ROOT=/opt/regrid-wrapper/spack-stack/spack

SHELL ["/bin/bash", "-c"]

RUN <<INSTALL_ALL
  set -eu
  . ./setup.sh
  spack compiler find
  spack external find rust curl perl git python cmake gettext findutils tar
  spack config add "packages:rust:buildable:false"
  spack config add "packages:curl:buildable:false"
  spack config add "packages:perl:buildable:false"
  spack config add "packages:git:buildable:false"
  spack config add "packages:python:buildable:false"
  spack config add "packages:cmake:buildable:false"
  spack config add "packages:gettext:buildable:false"
  spack config add "packages:findutils:buildable:false"
  spack config add "packages:tar:buildable:false"
  spack env create regrid-wrapper
  spack env activate regrid-wrapper
  spack config add "concretizer:unify:when_possible"
  spack add esmf@8.9.1+python py-netcdf4+mpi py-pytest py-pydantic@2.10.1 nccmp py-xarray
  spack concretize
  spack install --fail-fast
  spack gc -y
  spack clean --all
INSTALL_ALL

# 1. Create a system user (-r) with no password
# We also create a home directory (-m)
RUN useradd -r -m rw

# 2. (Optional) Set up your app directory and give the user ownership
WORKDIR /opt/regrid-wrapper
RUN chown -R rw:rw /opt/regrid-wrapper

# 3. Switch to the non-root user
USER rw

WORKDIR /opt/regrid-wrapper/spack-stack
RUN <<INSTALL_PYDANTIC_SETTINGS
  set -eu
  . ./setup.sh
  spack env activate regrid-wrapper
  spack add py-pydantic-settings
  spack concretize
  spack install --fail-fast
  spack gc -y
  spack clean --all
INSTALL_PYDANTIC_SETTINGS
